<template>
  <div class="alpha sp-mt-6 sp-py-6">
    <div class="container">
      <div class="row justify-content-md-between align-items-md-center">
        <div class="col-lg-2 col-md-3 col-12">
          <div
            class="alpha_question_image"
            data-aos="fade-up"
            data-aos-delay="0"
          ></div>
        </div>
        <div class="col-lg-10 col-md-9 col-12">
          <h1 class="alpha-title my-3" data-aos="fade-up" data-aos-delay="1">
            What are dipoleDIAMOND's IPs?
          </h1>
          <p class="alpha-sub my-3" data-aos="fade-up" data-aos-delay="2">
            dipoleDIAMOND's IPs are the first step in the process of
            understanding the molecular structure of a protein. They are
            generated by the dipole-dipole interaction of the protein's backbone
            atoms. The dipole-dipole interaction is a unique interaction that
            allows the protein to be studied in a way that is not possible with
            the molecular structure alone.
          </p>
        </div>
      </div>
    </div>
  </div>
</template>

<script>
export default {
  name: "Alpha",
  created() {},
  data() {
    return {};
  },
  props: {},
  methods: {},
};
</script>

<style lang="scss" scoped></style>