<template>
  <div class="container sp-mt-4 sp-py-6">
    <div class="row justify-content-lg-between align-items-lg-center">
      <div class="col-lg-4">
        <h1 class="cat-title" data-aos="fade-up" data-aos-delay="0">
          Find the right product for your business
        </h1>
        <p class="cat-body my-4" data-aos="fade-up" data-aos-delay="1">
          dipoleDIAMOND's IPs are the first step in the process of understanding
          the molecular structure of a protein. They are generated by the
          dipole-dipole interaction of the protein's backbone atoms. The
          dipole-dipole interaction is a unique interaction that allows the
          protein to be studied in a way that is not possible with the molecular
          structure alone.
        </p>
      </div>
      <!--  -->
      <div class="col-lg-8 col-cat-8">
        <div class="row my-4">
          <div class="col-sm-6 col-12 my-4">
            <div
              class="card category category-1"
              data-aos="fade-up"
              data-aos-delay="1"
            >
              <div
                class="icon d-flex justify-content-center align-items-center"
              >
                <i class="fa fa-money"></i>
              </div>
              <h4 class="card-title mt-4 mb-3">Finance</h4>
              <div class="list">
                <div class="text">Vendor Payment Process</div>
                <div class="text">Reimbursement Process</div>
                <div class="text">Expensing and Reporting Process</div>
              </div>
            </div>
          </div>
          <!--  -->
          <div class="col-sm-6 col-12 my-4">
            <div
              class="card category category-2"
              data-aos="fade-up"
              data-aos-delay="3"
            >
              <div
                class="icon d-flex justify-content-center align-items-center"
              >
                <i class="fa fa-user-circle"></i>
              </div>
              <h4 class="card-title mt-4 mb-3">Operations/Admin</h4>
              <div class="list">
                <div class="text">Vendor Onboarding Process</div>
                <div class="text">Material/Store Requistion</div>
                <div class="text">Inventory Management Process</div>
              </div>
            </div>
          </div>
        </div>

        <!--  -->
        <div class="row my-4">
          <div class="col-sm-6 col-12 my-4">
            <div
              class="card category category-3"
              data-aos="fade-up"
              data-aos-delay="5"
            >
              <div
                class="icon d-flex justify-content-center align-items-center"
              >
                <i class="fa fa-money"></i>
              </div>
              <h4 class="card-title mt-4 mb-3">Human Resources</h4>
              <div class="list">
                <div class="text">
                  Employee Onboarding and Offboarding Proc..
                </div>
                <div class="text">Leave Request Process</div>
                <div class="text">Appraisal and KPI Definition Process</div>
              </div>
            </div>
          </div>
          <!--  -->
          <div class="col-sm-6 col-12 my-4">
            <div
              class="card category category-4"
              data-aos="fade-up"
              data-aos-delay="8"
            >
              <div
                class="icon d-flex justify-content-center align-items-center"
              >
                <i class="fa fa-user-circle"></i>
              </div>
              <h4 class="card-title mt-4 mb-3">Operations/Admin</h4>
              <div class="list">
                <div class="text">Vendor Onboarding Process</div>
                <div class="text">Material/Store Requistion</div>
                <div class="text">Inventory Management Process</div>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</template>

<script>
export default {
  name: "Categories",
  created() {},
  data() {
    return {};
  },
  props: {},
  methods: {},
};
</script>

<style lang="scss" scoped></style>